### ISSUE TITLE
Como obter token do cartão de credito

### ISSUE THREAD

**Issue by lucasdiedrich** [wchagas/pagseguro-node#1]
Primeiramente parabéns pela biblioteca, segundo, como eu faço para obter o token informado [nessa linha](https://github.com/wchagas/pagseguro-node/blob/79ac8e06bdef7af5701086736634cbca7108cc80/example/transaction/creditCard.js#L12)? 

Entendo que deve ser uma criptografia com os dados do cartão informado, problema que não achei na documentacao se existe esse metodo no codigo fonte.

Obrigado

**Comment by wchagas** [comment]
Valeu Lucas, 

Neste caso (checkout transparente), o token deve ser obtido pelo front-end. Eu criei um lib em ReactJs que facilita esse trabalho: [pagseguro-react](https://github.com/wchagas/pagseguro-react). Caso contrário, você precisará fazer a integração por conta própria. Veja a documentação do pagseguro:  [checkout transparente](https://dev.pagseguro.uol.com.br/docs/checkout-web-usando-a-sua-tela).

Em breve vou integrar o checkout (que redireciona o usuário para o pagseguro). Mas no momento só funciona com checkout transparente, o que te obriga a ter integração também no front-end.

Qualquer coisa dá um toque. Abs

**Comment by lucasdiedrich** [comment]
Perfeito, grato pela explicação, estava procurando algo para fazer no lado do servidor, visto que o pagseguro não suporta este tipo de venda direta (sempre tem que haver um front) estou verificando outros gateways de pagamento, pagarme é uma boa.
