### ISSUE TITLE
Erro ao importar lib

### ISSUE THREAD

**Issue by dennerevaldt** [wchagas/pagseguro-node#2]
Primeiramente parabéns pela contribuição e trabalho!

Estou obtendo uma exceção ao importar sua lib no projeto, o seguinte erro é exposto:
`Error: Cannot find module '@babel/runtime/helpers/interopRequireDefault'`

As únicas coisas que fiz foram:
- Instalar através do comando `npm install nodejs-pagseguro`;
- Importar em um arquivo comum com `const pagseguro = require("nodejs-pagseguro")`;

Se necessário, estou utilizando as seguinte versões:
- Node: 10.15.3;
- NPM: 6.9.0;

O que pode estar havendo de errado?

**Comment by wchagas** [comment]
Valeu cara. Preciso trabalhar mais nesse projeto, mas ando sem tempo. 

Estava faltanto uma dependência, atualiza pra **v1.0.5**, acredito que vai resolver.

Se tiver dúvidas pra implementar pode dar um toque no hangout (chagaswc89@gmail.com).

Valeu pelo toque.

**Comment by dennerevaldt** [comment]
Resolvido @wchagas! Valeu!
