### ISSUE TITLE
IncomingMessage no console log mostra muitos dados.

### ISSUE THREAD

**Issue by sebastiaorealino** [wchagas/pagseguro-node#3]
Parabéns pelo trabalho. Mexi pouco com o projeto, mas o pelo pouco que vi, está muito bom.
Não é uma issue, seria um "improvement".

Ao criar uma sessão (já no .connect(config)) é exibida no console uma grande contidade de logs.
encapsulada em:
```
IncomingMessage {
...
}
```

Seria bom se existisse uma opcção no config para que as mensagens não fossem exibidas mesmo no ambiente de "dev".

Forte abraço!

**Comment by wchagas** [comment]
Obrigado pelo feedback Sebastião,

Concordo com você, ainda não dei atenção a esses detalhes, mas certamente vou seguir suas recomendações. Assim que liberar um tempo por aqui (espero que essa semana) vou me dedicar a esse projeto.

Obrigado mais uma vez. Abraço
