### ISSUE TITLE
em producao tem uma url impedindo o retorno da notificacao

### ISSUE THREAD

**Issue by thelucasgarcia** [wchagas/pagseguro-node#6]
estou usando em producao e reparei que as urls de producao de notificacao estao com uma barra no final o que impede o retorno da notificacao e pois o mesmo se encontra no estado 404

transaction: {
    search: "v3/transactions",
    //abandoned: 'v2/transactions' TODO: use?
    directPayment: "v2/transactions",
    code: "v2/transactions",
    refund: "v2/transactions/refunds/",
    cancel: "v2/transactions/cancels/",
    notification: "v3/transactions/notifications/"
  },

poderia tirar as barras?

**Comment by lucaspinheirogit** [comment]
Também estou com o mesmo problema @wchagas

**Comment by wchagas** [comment]
@lucaspinheirogit  e @thelucasgarcia obrigado por notificarem e corrigirem. Aprovei o PR podem testar?
